INFO 2025-03-12 09:19:02,727 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/slayd/settings.py changed, reloading.
INFO 2025-03-12 09:19:19,353 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 09:26:00,026 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py changed, reloading.
INFO 2025-03-12 09:26:16,213 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 09:27:42,782 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 09:28:39,452 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 09:29:19,772 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 200 29052
INFO 2025-03-12 09:54:21,821 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/slayd/settings.py changed, reloading.
INFO 2025-03-12 09:54:38,558 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 09:57:50,082 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py changed, reloading.
INFO 2025-03-12 09:58:07,856 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 09:58:20,224 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/urls.py changed, reloading.
INFO 2025-03-12 09:58:33,335 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 10:00:48,556 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/slayd/settings.py changed, reloading.
INFO 2025-03-12 10:03:08,110 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 10:03:19,485 credentials Found credentials in shared credentials file: ~/.aws/credentials
INFO 2025-03-12 10:03:19,748 metrics Successfully created CloudWatch client
ERROR 2025-03-12 10:03:19,748 metrics Failed to put CloudWatch metric: type object 'datetime.datetime' has no attribute 'UTC'
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 54, in put_metric
    'Timestamp': datetime.now(datetime.UTC)
                              ^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'UTC'
ERROR 2025-03-12 10:03:19,749 metrics Metric details - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}, {'Name': 'Method', 'Value': 'GET'}]
ERROR 2025-03-12 10:03:19,917 metrics Failed to put CloudWatch metric: type object 'datetime.datetime' has no attribute 'UTC'
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 54, in put_metric
    'Timestamp': datetime.now(datetime.UTC)
                              ^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'UTC'
ERROR 2025-03-12 10:03:19,930 metrics Metric details - Name: ProcessingTime, Value: 165.99702835083008, Dimensions: [{'Name': 'Endpoint', 'Value': 'SimilarProductsView'}]
ERROR 2025-03-12 10:03:20,033 metrics Failed to put CloudWatch metric: type object 'datetime.datetime' has no attribute 'UTC'
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 54, in put_metric
    'Timestamp': datetime.now(datetime.UTC)
                              ^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'UTC'
ERROR 2025-03-12 10:03:20,033 metrics Metric details - Name: ResponseTime, Value: 568.2179927825928, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}]
ERROR 2025-03-12 10:03:20,033 metrics Failed to put CloudWatch metric: type object 'datetime.datetime' has no attribute 'UTC'
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 54, in put_metric
    'Timestamp': datetime.now(datetime.UTC)
                              ^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'UTC'
ERROR 2025-03-12 10:03:20,033 metrics Metric details - Name: StatusCode, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}, {'Name': 'StatusCode', 'Value': '422'}]
WARNING 2025-03-12 10:03:20,034 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 422 11087
INFO 2025-03-12 10:04:13,479 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/slayd/settings.py changed, reloading.
INFO 2025-03-12 10:04:30,246 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 10:04:34,455 metrics Successfully created CloudWatch client
ERROR 2025-03-12 10:04:34,456 metrics Failed to put CloudWatch metric: type object 'datetime.datetime' has no attribute 'UTC'
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 54, in put_metric
    'Timestamp': datetime.now(datetime.UTC)
                              ^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'UTC'
ERROR 2025-03-12 10:04:34,457 metrics Metric details - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}, {'Name': 'Method', 'Value': 'GET'}]
ERROR 2025-03-12 10:04:34,519 metrics Failed to put CloudWatch metric: type object 'datetime.datetime' has no attribute 'UTC'
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 54, in put_metric
    'Timestamp': datetime.now(datetime.UTC)
                              ^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'UTC'
ERROR 2025-03-12 10:04:34,520 metrics Metric details - Name: ProcessingTime, Value: 61.3558292388916, Dimensions: [{'Name': 'Endpoint', 'Value': 'SimilarProductsView'}]
ERROR 2025-03-12 10:04:34,798 metrics Failed to put CloudWatch metric: type object 'datetime.datetime' has no attribute 'UTC'
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 54, in put_metric
    'Timestamp': datetime.now(datetime.UTC)
                              ^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'UTC'
ERROR 2025-03-12 10:04:34,798 metrics Metric details - Name: ResponseTime, Value: 412.33205795288086, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}]
ERROR 2025-03-12 10:04:34,798 metrics Failed to put CloudWatch metric: type object 'datetime.datetime' has no attribute 'UTC'
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 54, in put_metric
    'Timestamp': datetime.now(datetime.UTC)
                              ^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'UTC'
ERROR 2025-03-12 10:04:34,798 metrics Metric details - Name: StatusCode, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}, {'Name': 'StatusCode', 'Value': '422'}]
WARNING 2025-03-12 10:04:34,799 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 422 11087
INFO 2025-03-12 10:05:22,988 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py changed, reloading.
INFO 2025-03-12 10:05:40,298 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 10:06:01,070 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py changed, reloading.
INFO 2025-03-12 10:06:16,033 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 10:06:19,814 metrics Successfully created CloudWatch client
ERROR 2025-03-12 10:06:20,278 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:06:20,287 metrics Metric details - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}, {'Name': 'Method', 'Value': 'GET'}]
ERROR 2025-03-12 10:06:20,492 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:06:20,493 metrics Metric details - Name: ProcessingTime, Value: 166.6879653930664, Dimensions: [{'Name': 'Endpoint', 'Value': 'SimilarProductsView'}]
ERROR 2025-03-12 10:06:20,620 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:06:20,621 metrics Metric details - Name: ResponseTime, Value: 834.5839977264404, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}]
ERROR 2025-03-12 10:06:20,653 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:06:20,653 metrics Metric details - Name: StatusCode, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}, {'Name': 'StatusCode', 'Value': '422'}]
WARNING 2025-03-12 10:06:20,654 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 422 11087
INFO 2025-03-12 10:08:13,947 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 10:08:52,771 metrics Successfully created CloudWatch client
ERROR 2025-03-12 10:08:53,592 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:08:53,596 metrics Metric details - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}, {'Name': 'Method', 'Value': 'GET'}]
ERROR 2025-03-12 10:08:53,797 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:08:53,797 metrics Metric details - Name: ProcessingTime, Value: 156.74805641174316, Dimensions: [{'Name': 'Endpoint', 'Value': 'SimilarProductsView'}]
ERROR 2025-03-12 10:08:53,874 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:08:53,874 metrics Metric details - Name: ResponseTime, Value: 1187.3857975006104, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}]
ERROR 2025-03-12 10:08:53,912 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:08:53,916 metrics Metric details - Name: StatusCode, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}, {'Name': 'StatusCode', 'Value': '422'}]
WARNING 2025-03-12 10:08:53,916 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 422 11087
INFO 2025-03-12 10:11:54,638 autoreload Watching for file changes with StatReloader
INFO 2025-03-12 10:11:59,592 metrics Successfully created CloudWatch client
ERROR 2025-03-12 10:11:59,890 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:11:59,894 metrics Metric details - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}, {'Name': 'Method', 'Value': 'GET'}]
ERROR 2025-03-12 10:12:00,351 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:12:00,353 metrics Metric details - Name: ProcessingTime, Value: 251.86610221862793, Dimensions: [{'Name': 'Endpoint', 'Value': 'SimilarProductsView'}]
ERROR 2025-03-12 10:12:00,668 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/utils/metrics.py", line 47, in put_metric
    client.put_metric_data(**metric_data)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
ERROR 2025-03-12 10:12:00,668 metrics Metric details - Name: ResponseTime, Value: 1093.5957431793213, Dimensions: [{'Name': 'Endpoint', 'Value': '/api/similar-products/'}]
ERROR 2025-03-12 10:12:00,703 metrics Failed to put CloudWatch metric: An error occurred (AccessDenied) when calling the PutMetricData operation: User: arn:aws:iam::739275440812:user/s3-full-local is not authorized to perform: cloudwatch:PutMetricData because no identity-based policy allows the cloudwatch:PutMetricData action
Traceback (most recent call last):
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/generics.py", line 212, in get
    return self.retrieve(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/Users/sparsh/Documents/workspace/dev/slayd/feed/serializers.py", line 75, in get_sub_curations
    return CurationSerializer(obj.sub_curations.all(), many=True).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/Users/sparsh/Documents/workspace/dev/slayd/feed/serializers.py", line 62, in get_items
    return ItemSerializer(obj.component_items.all().values_list('item', flat=True), many=True).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `name` on serializer `ItemSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `int` instance.
Original exception text was: 'int' object has no attribute 'name'.
ERROR 2025-02-22 12:59:46,066 basehttp "GET /api/curation/10/ HTTP/1.1" 500 192046
INFO 2025-02-22 13:00:36,457 autoreload /Users/sparsh/Documents/workspace/dev/slayd/feed/views.py changed, reloading.
INFO 2025-02-22 13:00:36,815 autoreload Watching for file changes with StatReloader
ERROR 2025-02-22 13:00:45,710 log Internal Server Error: /api/curation/10/
Traceback (most recent call last):
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/generics.py", line 212, in get
    return self.retrieve(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/Users/sparsh/Documents/workspace/dev/slayd/feed/serializers.py", line 75, in get_sub_curations
    return CurationSerializer(obj.sub_curations.all(), many=True).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "/Users/sparsh/Documents/workspace/dev/slayd/feed/serializers.py", line 62, in get_items
    return ItemSerializer(obj.component_items.all().values_list('item', flat=True), many=True).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `name` on serializer `ItemSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `int` instance.
Original exception text was: 'int' object has no attribute 'name'.
ERROR 2025-02-22 13:00:45,711 basehttp "GET /api/curation/10/ HTTP/1.1" 500 192046
INFO 2025-02-22 13:01:21,024 autoreload /Users/sparsh/Documents/workspace/dev/slayd/feed/serializers.py changed, reloading.
INFO 2025-02-22 13:01:21,332 autoreload Watching for file changes with StatReloader
INFO 2025-02-22 13:01:22,520 autoreload /Users/sparsh/Documents/workspace/dev/slayd/feed/serializers.py changed, reloading.
INFO 2025-02-22 13:01:22,703 autoreload Watching for file changes with StatReloader
INFO 2025-02-22 13:01:26,094 basehttp "GET /api/curation/10/ HTTP/1.1" 200 23206
WARNING 2025-02-22 13:02:36,039 basehttp "GET /curations/10 HTTP/1.1" 404 2660
WARNING 2025-02-22 13:02:36,040 basehttp "GET /curations/10 HTTP/1.1" 404 2660
WARNING 2025-02-22 13:03:44,670 basehttp "GET /curations/10 HTTP/1.1" 404 2660
WARNING 2025-02-22 13:03:58,842 basehttp "GET /curations/10 HTTP/1.1" 404 2660
WARNING 2025-02-22 13:03:58,843 basehttp "GET /curations/10 HTTP/1.1" 404 2660
WARNING 2025-02-22 13:04:17,207 basehttp "GET /api/curations/10 HTTP/1.1" 404 4787
INFO 2025-02-22 13:04:34,411 basehttp "GET /api/curation/10/ HTTP/1.1" 200 4606
INFO 2025-02-22 13:04:38,085 basehttp "GET /api/curation/10/ HTTP/1.1" 200 4606
INFO 2025-02-22 13:04:38,085 basehttp "GET /api/curation/10/ HTTP/1.1" 200 4606
INFO 2025-02-22 13:04:56,089 basehttp "GET /api/curation/10/ HTTP/1.1" 200 23206
INFO 2025-03-07 07:51:15,553 autoreload Watching for file changes with StatReloader
WARNING 2025-03-07 07:53:55,267 basehttp "GET /api/similar-products/?image_url=https://littleboxindia.com/cdn/shop/files/69702083d3f85dd0abc207a898755f13_540x.webp?v=1741080147&search_type=image HTTP/1.1" 404 4932
INFO 2025-03-07 07:54:10,269 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/urls.py changed, reloading.
INFO 2025-03-07 07:54:39,381 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 08:01:07,556 basehttp "GET /api/similar-products/?image_url=https://littleboxindia.com/cdn/shop/files/69702083d3f85dd0abc207a898755f13_540x.webp?v=1741080147&search_type=combined_75 HTTP/1.1" 200 19161
INFO 2025-03-07 08:01:07,561 basehttp "GET /api/similar-products/?image_url=https://littleboxindia.com/cdn/shop/files/69702083d3f85dd0abc207a898755f13_540x.webp?v=1741080147&search_type=concat HTTP/1.1" 200 19199
INFO 2025-03-07 08:01:07,562 basehttp "GET /api/similar-products/?image_url=https://littleboxindia.com/cdn/shop/files/69702083d3f85dd0abc207a898755f13_540x.webp?v=1741080147&search_type=image HTTP/1.1" 200 19115
INFO 2025-03-07 08:05:57,887 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 08:06:11,957 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 08:11:53,894 basehttp "GET /api/similar-products/?image_url=https://littleboxindia.com/cdn/shop/files/69702083d3f85dd0abc207a898755f13_540x.webp?v=1741080147&search_type=image HTTP/1.1" 200 19109
INFO 2025-03-07 08:11:53,952 basehttp "GET /api/similar-products/?image_url=https://littleboxindia.com/cdn/shop/files/69702083d3f85dd0abc207a898755f13_540x.webp?v=1741080147&search_type=combined_75 HTTP/1.1" 200 19120
INFO 2025-03-07 08:11:54,163 basehttp "GET /api/similar-products/?image_url=https://littleboxindia.com/cdn/shop/files/69702083d3f85dd0abc207a898755f13_540x.webp?v=1741080147&search_type=concat HTTP/1.1" 200 19297
INFO 2025-03-07 08:11:57,362 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 08:12:17,200 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 08:23:08,338 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=concat HTTP/1.1" 200 19393
INFO 2025-03-07 08:23:08,338 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=image HTTP/1.1" 200 19206
INFO 2025-03-07 08:23:08,339 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 200 19505
INFO 2025-03-07 08:36:23,089 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 08:36:38,080 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 08:37:50,528 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 08:38:04,415 autoreload Watching for file changes with StatReloader
ERROR 2025-03-07 08:38:51,334 log Internal Server Error: /api/similar-products/
ERROR 2025-03-07 08:38:51,335 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=image HTTP/1.1" 500 10978
INFO 2025-03-07 08:41:17,661 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
ERROR 2025-03-07 08:42:55,082 log Internal Server Error: /api/similar-products/
ERROR 2025-03-07 08:42:55,130 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 500 11008
INFO 2025-03-07 08:43:47,943 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 08:45:24,632 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 08:45:39,830 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 08:48:14,963 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 08:48:28,933 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 08:49:11,439 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 08:49:24,354 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 08:49:46,964 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=image HTTP/1.1" 200 18260
ERROR 2025-03-07 08:53:13,748 log Internal Server Error: /api/similar-products/
ERROR 2025-03-07 08:53:13,751 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=concat HTTP/1.1" 500 10983
ERROR 2025-03-07 08:53:13,943 log Internal Server Error: /api/similar-products/
ERROR 2025-03-07 08:53:13,943 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 500 11008
INFO 2025-03-07 08:55:31,845 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 08:55:45,445 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 09:01:05,790 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 200 18608
INFO 2025-03-07 09:01:05,861 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=concat HTTP/1.1" 200 18605
INFO 2025-03-07 18:58:08,386 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 18:59:10,416 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/urls.py changed, reloading.
INFO 2025-03-07 18:59:26,976 autoreload Watching for file changes with StatReloader
ERROR 2025-03-07 19:00:08,799 log Internal Server Error: /api/similar-products/
Traceback (most recent call last):
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/utils/functional.py", line 32, in __call__
    return self.__value__
           ^^^^^^^^^^^^^^
AttributeError: 'ChannelPromise' object has no attribute '__value__'. Did you mean: '__call__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/connection.py", line 459, in _ensure_connection
    return retry_over_time(
           ^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/connection.py", line 934, in _connection_factory
    self._connection = self._establish_connection()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/transport/pyamqp.py", line 203, in establish_connection
    conn.connect()
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/amqp/connection.py", line 324, in connect
    self.transport.connect()
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/amqp/transport.py", line 132, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/amqp/transport.py", line 187, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/views.py", line 223, in get
    task = find_similar_products.delay(image_url, top_k, search_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/celery/app/task.py", line 594, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/celery/app/base.py", line 801, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/celery/app/amqp.py", line 518, in send_task_message
    ret = producer.publish(
          ^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/messaging.py", line 186, in publish
    return _publish(
           ^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/connection.py", line 556, in _ensured
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/messaging.py", line 195, in _publish
    channel = self.channel
              ^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/messaging.py", line 218, in _get_channel
    channel = self._channel = channel()
                              ^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/utils/functional.py", line 34, in __call__
    value = self.__value__ = self.__contract__()
                             ^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/messaging.py", line 234, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/connection.py", line 953, in default_channel
    self._ensure_connection(**conn_opts)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/connection.py", line 458, in _ensure_connection
    with ctx():
  File "/Users/sparsh/miniforge3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: [Errno 61] Connection refused
ERROR 2025-03-07 19:00:08,804 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 500 237114
INFO 2025-03-07 19:52:00,024 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 19:52:22,062 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/views.py changed, reloading.
INFO 2025-03-07 19:52:47,320 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 19:54:01,987 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 19:54:38,315 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/urls.py changed, reloading.
INFO 2025-03-07 19:54:54,699 autoreload Watching for file changes with StatReloader
ERROR 2025-03-07 19:55:00,898 log Internal Server Error: /api/similar-products/
Traceback (most recent call last):
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py", line 42, in _initialize
    self.fclip = settings.FASHIONCLIP_MODEL
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/conf/__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'FASHIONCLIP_MODEL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/miniforge3/lib/python3.12/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/views.py", line 213, in __init__
    self.searcher = SimilaritySearcher()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py", line 18, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py", line 24, in __init__
    self._initialize()  # Call initialize in __init__
    ^^^^^^^^^^^^^^^^^^
  File "/Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py", line 71, in _initialize
    raise RuntimeError(f"Failed to initialize SimilaritySearcher: {str(e)}")
RuntimeError: Failed to initialize SimilaritySearcher: 'Settings' object has no attribute 'FASHIONCLIP_MODEL'
ERROR 2025-03-07 19:55:00,908 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 500 97828
INFO 2025-03-07 19:56:47,521 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/slayd/settings.py changed, reloading.
INFO 2025-03-07 19:57:05,630 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 19:57:07,956 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/apps.py changed, reloading.
INFO 2025-03-07 19:57:25,645 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 19:59:49,577 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 200 18608
INFO 2025-03-07 20:01:43,764 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 20:01:58,367 autoreload Watching for file changes with StatReloader
ERROR 2025-03-07 20:02:26,941 log Internal Server Error: /api/similar-products/
ERROR 2025-03-07 20:02:26,941 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 500 11008
INFO 2025-03-07 20:03:27,949 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-07 20:03:43,706 autoreload Watching for file changes with StatReloader
INFO 2025-03-07 20:04:51,450 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 200 18608
INFO 2025-03-08 07:46:59,724 autoreload Watching for file changes with StatReloader
INFO 2025-03-08 07:47:16,001 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 200 19630
INFO 2025-03-08 08:04:44,408 autoreload Watching for file changes with StatReloader
INFO 2025-03-08 08:05:42,733 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/views.py changed, reloading.
INFO 2025-03-08 08:05:55,608 autoreload Watching for file changes with StatReloader
INFO 2025-03-08 08:06:19,143 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/urls.py changed, reloading.
INFO 2025-03-08 08:06:32,429 autoreload Watching for file changes with StatReloader
WARNING 2025-03-08 08:06:49,615 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2024/08/2711083633df5959/NM-IN-56-DRS-24-APR-5068-WHITE(1)-876x1334.webp&search_type=concat HTTP/1.1" 422 11036
INFO 2025-03-08 08:08:31,820 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/feed/utils/similarity_search.py changed, reloading.
INFO 2025-03-08 08:08:46,080 autoreload Watching for file changes with StatReloader
INFO 2025-03-08 08:09:03,448 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2024/08/2711083633df5959/NM-IN-56-DRS-24-APR-5068-WHITE(1)-876x1334.webp&search_type=concat HTTP/1.1" 200 17672
WARNING 2025-03-08 08:10:07,592 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/03/06090852c6b94f8a/NM-PRC-25-DRS-25-MAR-14950-BLACK(1)-765x765.webp%20765w,%20https://assets.newme.asia/wp-content/uploads/2025/03/06090852c6b94f8a/NM-PRC-25-DRS-25-MAR-14950-BLACK(1)-800x800.webp&search_type=concat HTTP/1.1" 400 11675
INFO 2025-03-08 08:10:40,930 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/03/06090852c6b94f8a/NM-PRC-25-DRS-25-MAR-14950-BLACK(1)-765x765.webp&search_type=concat HTTP/1.1" 200 18576
INFO 2025-03-08 08:28:45,328 autoreload Watching for file changes with StatReloader
INFO 2025-03-08 10:57:12,707 autoreload Watching for file changes with StatReloader
WARNING 2025-03-08 10:57:56,580 basehttp "GET / HTTP/1.1" 404 2606
INFO 2025-03-08 10:58:14,844 basehttp "GET /api/similar-products/?image_url=https://assets.newme.asia/wp-content/uploads/2025/02/19093826c5e812ff/NM-IN-56-DRS-24-SEP-9428-YELLOW(1)-889x1334.webp&search_type=combined_75 HTTP/1.1" 200 29052
INFO 2025-03-08 12:42:09,797 autoreload Watching for file changes with StatReloader
INFO 2025-03-08 12:42:29,678 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/account/views.py changed, reloading.
INFO 2025-03-08 12:42:42,652 autoreload Watching for file changes with StatReloader
INFO 2025-03-08 12:43:22,791 basehttp "GET /account/webhook/?hub.mode=subscribe&hub.verify_token=slayd&hub.challenge=CHALLENGE123 HTTP/1.1" 200 12
WARNING 2025-03-08 12:43:35,518 basehttp "GET /account/webhook/?hub.mode=subscribe&hub.verify_token=hello&hub.challenge=CHALLENGE123 HTTP/1.1" 403 9
INFO 2025-03-17 10:47:40,608 autoreload Watching for file changes with StatReloader
INFO 2025-03-17 10:48:00,790 metrics [LOCAL] Metric - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/'}, {'Name': 'Method', 'Value': 'GET'}]
INFO 2025-03-17 10:48:00,830 metrics [LOCAL] Metric - Name: ResponseTime, Value: 41.465044021606445, Dimensions: [{'Name': 'Endpoint', 'Value': '/'}]
INFO 2025-03-17 10:48:00,831 metrics [LOCAL] Metric - Name: StatusCode, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/'}, {'Name': 'StatusCode', 'Value': '404'}]
WARNING 2025-03-17 10:48:00,833 basehttp "GET / HTTP/1.1" 404 2759
INFO 2025-03-17 10:48:02,003 metrics [LOCAL] Metric - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/favicon.ico'}, {'Name': 'Method', 'Value': 'GET'}]
INFO 2025-03-17 10:48:02,011 metrics [LOCAL] Metric - Name: ResponseTime, Value: 10.248184204101562, Dimensions: [{'Name': 'Endpoint', 'Value': '/favicon.ico'}]
INFO 2025-03-17 10:48:02,011 metrics [LOCAL] Metric - Name: StatusCode, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/favicon.ico'}, {'Name': 'StatusCode', 'Value': '404'}]
WARNING 2025-03-17 10:48:02,012 basehttp "GET /favicon.ico HTTP/1.1" 404 2810
INFO 2025-03-17 10:48:07,954 metrics [LOCAL] Metric - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/instagram'}, {'Name': 'Method', 'Value': 'GET'}]
INFO 2025-03-17 10:48:07,965 metrics [LOCAL] Metric - Name: ResponseTime, Value: 11.284112930297852, Dimensions: [{'Name': 'Endpoint', 'Value': '/instagram'}]
INFO 2025-03-17 10:48:07,965 metrics [LOCAL] Metric - Name: StatusCode, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/instagram'}, {'Name': 'StatusCode', 'Value': '404'}]
WARNING 2025-03-17 10:48:07,965 basehttp "GET /instagram HTTP/1.1" 404 2804
INFO 2025-03-17 10:48:12,318 metrics [LOCAL] Metric - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/instagram/'}, {'Name': 'Method', 'Value': 'GET'}]
INFO 2025-03-17 10:48:12,331 metrics [LOCAL] Metric - Name: ResponseTime, Value: 14.430046081542969, Dimensions: [{'Name': 'Endpoint', 'Value': '/instagram/'}]
INFO 2025-03-17 10:48:12,332 metrics [LOCAL] Metric - Name: StatusCode, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/instagram/'}, {'Name': 'StatusCode', 'Value': '404'}]
WARNING 2025-03-17 10:48:12,333 basehttp "GET /instagram/ HTTP/1.1" 404 2931
INFO 2025-03-17 10:48:23,005 metrics [LOCAL] Metric - Name: RequestCount, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/instagram/webhook/'}, {'Name': 'Method', 'Value': 'GET'}]
INFO 2025-03-17 10:48:23,008 metrics [LOCAL] Metric - Name: ResponseTime, Value: 3.615140914916992, Dimensions: [{'Name': 'Endpoint', 'Value': '/instagram/webhook/'}]
INFO 2025-03-17 10:48:23,008 metrics [LOCAL] Metric - Name: StatusCode, Value: 1, Dimensions: [{'Name': 'Endpoint', 'Value': '/instagram/webhook/'}, {'Name': 'StatusCode', 'Value': '200'}]
INFO 2025-03-17 10:48:23,009 basehttp "GET /instagram/webhook/ HTTP/1.1" 200 18
INFO 2025-03-17 10:51:26,369 autoreload /Users/sparsh/Documents/workspace/dev/slayd-main/slayd/instagram_bot/views.py changed, reloading.
INFO 2025-03-17 10:51:51,808 autoreload Watching for file changes with StatReloader
